name = "ManyUICImGui"
uuid = "18e426b3-1956-47f5-93db-1e658e915efb"
authors = ["Sebastien Celles <s.celles@gmail.com>"]
version = "0.1.0"

[deps]
ManyUI = "4f14d67d-91c5-4d6b-929d-6ac291535b21"
ManyUITUI = "5c52c6f3-12e3-46fb-a0b2-3b2e56cfefb8"

[sources]
ManyUI = {url = "https://github.com/s-celles/ManyUI.jl.git"}
ManyUITUI = {url = "https://github.com/s-celles/ManyUITUI.jl.git"}
HarfBuzz = {url = "https://github.com/s-celles/HarfBuzz.jl.git"}

[compat]
Aqua = "0.8"
CImGui = "8"
GLFW = "3"
HarfBuzz = "0.1"
ManyUI = "0.1"
ManyUITUI = "0.1"
ModernGL = "1"
Test = "1"
TestItemRunner = "1"
julia = "1.12"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Aqua", "Test", "TestItemRunner"]

[weakdeps]
CImGui = "5d785b6c-b76f-510e-a07c-3070796c7e87"
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
HarfBuzz = "9e8b9c2b-5c3e-4e6f-b1a4-2c0f6b4f3e2a"
ModernGL = "66fc600b-dfda-50eb-8b99-91cfa97b1301"

[extensions]
ManyUICImGuiCImGuiExt = ["CImGui", "GLFW", "HarfBuzz", "ModernGL"]
