name = "ManyUICImGui"
uuid = "18e426b3-1956-47f5-93db-1e658e915efb"
authors = ["Sebastien Celles <s.celles@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.12"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
